FROM node:12.16
RUN npm install -g serve
COPY /app code
WORKDIR /code

ENV NODE_ENV=production
ENV REACT_APP_EXPERIMENTS_SERVICE="http://localhost:6300"
ENV REACT_APP_USER_ACTIVITY_SERVICE="http://localhost:6600"
ENV REACT_APP_AUTH_DOMAIN="grizzly-bear-dev.eu.auth0.com"
ENV REACT_APP_AUTH_CLIENT_ID="6m6D5qYQJp69OZShjYs6PzLmbQKuntK1"
ENV REACT_APP_AUTH_AUDIENCE="http://www.grizzlybear-experiments.com"

RUN npm ci
RUN npm run build
CMD ["serve", "-s", "build"]