apiVersion: "v1"
kind: "Service"
metadata:
  name: "dashboard"
  namespace: "default"
  labels:
    app: "dashboard"
spec:
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 5000
  selector:
    app: "dashboard"
  type: "NodePort"
